### ISSUE TITLE
trouble adding custom biomes

### ISSUE THREAD

**Issue by Aabyiswack** [dhyces/lunar-nether#2]
when i add new biomes to the under nether region some of the other biomes dont spawn, for example if i add 1 biome from the regions unexplored nether biomes, the minecraft:basalt_deltas doesnt spawn anymore.

its almost like there can only be 5 nether biomes at a time

**Comment by xbxbxb123** [comment]
Thanks for letting me know on curseforge, I think my notifications were turned off somehow. Anyways, the biome placement system for the nether is different from the one for the overworld, last I checked. Can you verify that whatever system you are using to add the biome works on its own? Additionally, if it is a datapack, it probably can't work, from my understanding.

**Comment by xbxbxb123** [comment]
More info from the original dev: This is almost definitely not Lunar Nether's fault. If this is happening, the most likely explanation is that you used the same number values as basalt deltas, so that your new biome is a closer match for the places that basalt deltas would appear than the basalt deltas themselves.

**Comment by xbxbxb123** [comment]
Issue was not with this mod

**Comment by Aabyiswack** [comment]
> More info from the original dev: This is almost definitely not Lunar Nether's fault. If this is happening, the most likely explanation is that you used the same number values as basalt deltas, so that your new biome is a closer match for the places that basalt deltas would appear than the basalt deltas themselves.

yup it wasnt, thank you i didnt know you needed to have different values for the biomes to spawn, now everything is working accordingly.
